#!/usr/bin/env bash

FILE_TITLE=""
for i in "$@"
do
  FILE_TITLE+="-$(echo "$i" | tr '[:upper:]' '[:lower:]')"
done

POST="$(date +%Y-%m-%d)${FILE_TITLE}.markdown"

if [ -f ${POST} ]; then
  echo "File already exists: ${POST}"
  exit
fi

echo -e """---
layout: post
title: \"$@\"
date: \"$(date +%Y-%m-%d\ %T\ %z)\"
---

""" >> ${POST}

vim ${POST}
